#!/bin/bash

## Files and cmd
FILE="/tmp/eww_dashboard_is_open"
CFG="$HOME/.config/eww/"
EWW=`which eww`

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	${EWW} daemon
	sleep 1
fi

## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
	${EWW} --config "$CFG" open-many \
		darken \
		clock \
	    system \
	    windowlist \
		power \
		status
else
	${EWW} --config "$CFG" close-all
	rm "$FILE"
fi
