#!/bin/sh

DIR=/home/ross/.dotfiles

# For folders, put it in the folder. Otherwise repeated applications will create further link
ln -sf $DIR/dunst ~/.config/
ln -sf $DIR/eww ~/.config/
ln -sf $DIR/hypr ~/.config/
ln -sf $DIR/nano ~/.config/
# ln -sf $DIR/powerline ~/.config/

ln -sf $DIR/git/gitconfig ~/.gitconfig
ln -sf $DIR/git/gitignore ~/.gitignore

# TODO: Where is this?!
# ln -sf $DIR/latex/ross.sty ~/texmf/tex/latex/commonstuff/ross.sty

ln -sf $DIR/stack/config.yaml ~/.stack/config.yaml

# ln -sf $DIR/tmux/tmux.conf

ln -sf $DIR/vscode/keybindings.json ~/.config/vscode/User/keybindings.json
ln -sf $DIR/vscode/settings.json ~/.config/vscode/User/settings.json

ln -sf $DIR/zsh/zprofile ~/.zprofile
ln -sf $DIR/zsh/zshenv ~/.zshenv
ln -sf $DIR/zsh/zshrc ~/.zshrc
