#!/bin/zsh
# This command disables the keyboard, touchpad, or touchscreen.
# Disabling the touchpad and keyboard is so that the touchscreen can be used in folded mode without pushing random buttons. 
# This script is bound to the power key. Luckily it is a separate device, so can be used to reactivate the keyboard.

COMPLETION="help setup toggle-keyboard toggle-touchscreen is_touchy"
BASHCOMPLETION='compctl -k "('$COMPLETION')" disable-input'

KEYBOARD_STATUS_FILE="$XDG_RUNTIME_DIR/keyboard.status"
SCREEN_STATUS_FILE="$XDG_RUNTIME_DIR/screen.status"
icon_name="/usr/share/icons/elementary/devices/48/input-keyboard.svg"


setup() {
if [ -z "$XDG_RUNTIME_DIR" ]; then
  export XDG_RUNTIME_DIR=/run/user/$(id -u)
  export KEYBOARD_STATUS_FILE="$XDG_RUNTIME_DIR/keyboard.status"
  export SCREEN_STATUS_FILE="$XDG_RUNTIME_DIR/screen.status"
fi
printf "true" >"$KEYBOARD_STATUS_FILE"
printf "false" >"$SCREEN_STATUS_FILE"
}

status() {
echo "Keyboard and touchpad enabled"
echo $(cat "$KEYBOARD_STATUS_FILE") 
echo "Touchscreen enabled"
echo $(cat "$SCREEN_STATUS_FILE") 
}

is_touchy() {
echo $(cat "$SCREEN_STATUS_FILE") 
}

toggle_keyboard() {
if [ $(cat "$KEYBOARD_STATUS_FILE") = "true" ]; then
    printf "false" >"$KEYBOARD_STATUS_FILE"
    notify-send "Input disabled" -i $icon_name -h string:synchronous:trackpad 
    hyprctl keyword '$LAPTOP_KB_ENABLED' "false" -r
    hyprctl keyword '$LAPTOP_TOUCHPAD_ENABLED' "false" -r
elif [ $(cat "$KEYBOARD_STATUS_FILE") = "false" ]; then
    printf "true" >"$KEYBOARD_STATUS_FILE"
    notify-send "Input enabled" -i $icon_name -h string:synchronous:trackpad 
    hyprctl keyword '$LAPTOP_KB_ENABLED' "true" -r
    hyprctl keyword '$LAPTOP_TOUCHPAD_ENABLED' "true" -r
fi
}

toggle_screen() {
if [ $(cat "$SCREEN_STATUS_FILE") = "true" ]; then
    printf "false" >"$SCREEN_STATUS_FILE"
    notify-send "Touchscreen disabled" -i $icon_name -h string:synchronous:trackpad 
    hyprctl keyword '$LAPTOP_TOUCHSCREEN_ENABLED' "false" -r
elif [ $(cat "$SCREEN_STATUS_FILE") = "false" ]; then
    printf "true" >"$SCREEN_STATUS_FILE"
    notify-send "Touchscreen enabled" -i $icon_name -h string:synchronous:trackpad 
    hyprctl keyword '$LAPTOP_TOUCHSCREEN_ENABLED' "true" -r
fi
}

# If the status file doesn't exist, run setup
if [ -z "$KEYBOARD_STATUS_FILE" ]; then
  setup
fi

case $1 in
"help")
	echo "Available options:"
    echo $COMPLETION
	;;

"--bashcompletion")
	echo $BASHCOMPLETION
	;;

"setup")
	setup
	;;

"is_touchy" | "status_eww")
	is_touchy
	;;

"toggle-keyboard")
    toggle_keyboard
	;;

"toggle-touchscreen")
    toggle_screen
	;;

"status"|"*")
	status
	;;
esac
