name: xmonad-config
version: '0.1.0.0'
synopsis: My Xmonad config
category: System
author: Ross Ogilvie
maintainer: ross@rossogilvie.id.au
license: BSD3
ghc-options:
- -threaded
- -rtsopts
- -with-rtsopts=-N
other-extensions:
- UnicodeSyntax
dependencies:
- base
- containers
- X11
- xmonad
- xmonad-contrib
executables:
  xmonad-x86_64-linux:
    main: xmonad.hs
    source-dirs: src
