#!/bin/sh

## There is a script in here, 30-dbus, that should start that session
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

#############
## Set up
#############
[ -f ~/.xprofile ] && source ~/.xprofile

##############
## Xmonad WM
##############
exec /home/ross/.xmonad/xmonad-x86_64-linux > /tmp/xmonad_runtime_log 2>&1
