#
# dotphiles : https://github.com/dotphiles/dotphiles
#
# Defines environment variables.
#
###############################
### env variables
###############################

# this is set at some point, but I need it set earlier for some startup scripts
export HOST="$(hostnamectl hostname)"

#change the default editor to nano
export EDITOR="nano"
#change merge program to meld
export DIFFPROG="meld"

#make firefox recognise touchscreen scrolling
MOZ_USE_XINPUT2=1

#Add my misc scripts to the path, and the current directory
typeset -U path
path=(/home/ross/.scripts /home/ross/.local/bin /home/ross/.ghcup/bin $path)

#Qt use gtk theme via qt5-styleplugins
export QT_QPA_PLATFORMTHEME="gtk2"
